### ISSUE TITLE
Not working with new package revision mechanism

### ISSUE THREAD

**Issue by osechet** [conan-io/conan-package-tools#361] opened 2019-03-28 12:32 UTC
### Description of Problem, Request, or Question
The conan package tools is not working with the new revision mechanism (https://docs.conan.io/en/latest/mastering/revisions.html): nothing is done during the upload step.

I tried to debug the process and I found the problem occurs because the package_id now includes the revision (i.e. foo/1.0.0@user/channel#revision) but the package tools still use the short reference (i.e. foo/1.0.0@user/channel) (see cpt/runner.py, l.116)

### Environment Details
* Conan Package Tools Version: **0.24.0**, **master**
* Operating System: **Linux**
* Operation System Version: **CentOS 7**
* Compiler+version: **gcc-7.3**
* Docker image: **N/A**
* Conan version: **conan 1.13.2**
* Python version: **python 3.6.7**

### Steps to reproduce (Include if Applicable)

* Set the CONAN_REVISIONS_ENABLED environment variable to 1.
* Run `python build.py`

**Comment by danimtb** [comment] 2019-03-28 12:55
Hi @osechet,

In theory, the only thing to make revisions work is to set the ``CONAN_REVISIONS_ENABLED=1``.
However, I see here https://github.com/conan-io/conan-package-tools/blob/43096ab4d7e66d73e040cdefc2f64dedd4e3ce47/cpt/runner.py#L116 that the representation of the reference will be different in that case.

So the issue is that the packages are not uploaded, right?

**Comment by uilianries** [comment] 2019-03-28 13:19
I can confirm the bug.

steps to reproduce:

	conan config set general.revisions_enabled=True
	conan conan new -s -cilc foo/0.1
    export CONAN_USERNAME=uilianries
    export CONAN_UPLOAD=https://api.bintray.com/conan/uilianries/conan
    export CONAN_PASSWORD=*****
    
CPT will skip the upload step. Thanks for reporting!

**Comment by danimtb** [comment] 2019-03-28 15:32
Thanks for checking a proposing the fix @uilianries. I see the PR with the fix is already merged. Please close this as solve in that case 😃 

P.S. That was quick man! 🥇

**Comment by uilianries** [comment] 2019-03-29 11:44
Closed by https://github.com/conan-io/conan-package-tools/pull/363

**Closed by uilianries** 2019-03-29 11:44 UTC
Labels: complex: low, component: build, priority: medium, stage: review, type: bug
